Repository open-spaced-repetition/fsrs4anki, pull requests merged in 2022-10, with the labels that each got.

#55 Feat/redesign difficulty
  fsrs4anki_optimizer.ipynb
  fsrs4anki_scheduler.js
Labels: enhancement

#60 Fix/constrain parameters
  fsrs4anki_optimizer.ipynb
  fsrs4anki_scheduler.js
Labels: invalid

#62 Feat/add fuzz to next intervals
  fsrs4anki_scheduler.js
Labels: enhancement

#64 Fix/constrain hard interval less than good interval
  fsrs4anki_scheduler.js
Labels: invalid

#65 Fix/relax post lapse stability
  fsrs4anki_optimizer.ipynb
Labels: invalid

#66 Feat/generate analysis of review logs
  fsrs4anki_optimizer.ipynb
Labels: enhancement

#68 Doc/add more explanation to optimizer
  fsrs4anki_optimizer.ipynb
Labels: documentation

#69 Feat/add comparison in simulator
  fsrs4anki_simulator.ipynb
Labels: enhancement

#72 Fix/anki hard interval >= last interval + 1
  fsrs4anki_simulator.ipynb
Labels: invalid

#73 Improve fuzz: even intervals distribution, keep proportions, toggleable
  fsrs4anki_scheduler.js
Labels: enhancement

#76 Feat/suggest optimal retention
  fsrs4anki_optimizer.ipynb
Labels: enhancement

#77 Feat/add leeches threshold and action to simulator
  fsrs4anki_simulator.ipynb
Labels: enhancement

#80 Fix/extend the range of retention to search
  fsrs4anki_optimizer.ipynb
Labels: invalid

#81 Fix/wrong weighted average
  fsrs4anki_optimizer.ipynb
Labels: invalid

#83 Fix/padding for missing difficulty
  fsrs4anki_optimizer.ipynb
Labels: bug

#85 Feat/count expected memorization
  fsrs4anki_simulator.ipynb
Labels: enhancement

#89 Fix/true repetition from revlog
  fsrs4anki_optimizer.ipynb
Labels: invalid
