Repository open-spaced-repetition/fsrs4anki, pull requests merged in 2023-02, with the labels that each got.

#130 Fix/display FSRS status on correct position
  fsrs4anki_scheduler.js
  fsrs4anki_scheduler_qt5.js
Labels: invalid

#134 Feat/replace repetitions with review time in optimization and simulation
  fsrs4anki_optimizer.ipynb
  fsrs4anki_simulator.ipynb
Labels: enhancement

#140 Fix/run scheduler after the card front has been rendered
  fsrs4anki_scheduler.js
  fsrs4anki_scheduler_qt5.js
Labels: bug

#147 Fix/wrong interval when setting revlog_start_date
  fsrs4anki_optimizer.ipynb
Labels: invalid

#159 Fix/NonExistentTimeError when floor
  fsrs4anki_optimizer.ipynb
Labels: bug

#150 Feat/decouple user deck parameters from code
  fsrs4anki_scheduler.js
  fsrs4anki_scheduler_qt5.js
Labels: enhancement

#170 remove dead code in review card again stability calculation
  fsrs4anki_scheduler.js
  fsrs4anki_scheduler_qt5.js
Labels: invalid

#171 Fix/remove "var w = " from the output of optimizer
  fsrs4anki_optimizer.ipynb
Labels: invalid
