Repository open-spaced-repetition/fsrs4anki, pull requests merged in 2023-11, with the labels that each got.

#527 Fix/apply max interval to SM-2
  fsrs4anki_optimizer.ipynb
  fsrs4anki_simulator.ipynb
Labels: bug

#536 Doc/clarify (re)learning steps recommendation
  docs/tutorial.md
Labels: documentation

#541 Doc/compatibility with learn now & grade now
  README.md
Labels: documentation, compatibility

#543 Added "The Ultra Short Version" section.md
  docs/tutorial.md
Labels: documentation

#544 Update tutorial.md
  README.md
  docs/tutorial.md
  docs/tutorial2.md
Labels: documentation
