Repository open-spaced-repetition/fsrs4anki, pull requests merged in 2023-04, with the labels that each got.

#201 Fix/tqdm notebook
  fsrs4anki_optimizer.ipynb
Labels: bug

#205 Fix/cut off incomplete revlogs in optimizer
  fsrs4anki_optimizer.ipynb
Labels: invalid

#210 Feat/read deckname & seed from ctx
  fsrs4anki_scheduler.js
  fsrs4anki_scheduler_qt5.js
Labels: enhancement

#212 Feat/Calibration graph
  fsrs4anki_optimizer.ipynb
Labels: enhancement

#229 Feat/add more metrics from sklearn
  fsrs4anki_optimizer.ipynb
Labels: enhancement

#230 Doc/add introduction for metrics
  fsrs4anki_optimizer.ipynb
Labels: documentation

#234 Fix/zero-divide-warning
  fsrs4anki_optimizer.ipynb
Labels: invalid

#232 Command line optimizer
  .gitignore
  fsrs4anki_optimizer.ipynb
  pip/Makefile
  pip/fsrs4anki_optimizer/__init__.py
  pip/fsrs4anki_optimizer/__main__.py
  pip/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  pip/requirements.txt
  pip/setup.py
  requirements.txt
Labels: enhancement
