Repository open-spaced-repetition/fsrs4anki, pull requests merged in 2023-06, with the labels that each got.

#276 fix typerror with next_day_starts_at
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
Labels: invalid

#279 Feat/mini batch & cross validation & bm-metric
  fsrs4anki_optimizer.ipynb
  package/Makefile
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/setup.py
Labels: enhancement

#280 Fix/typo & dependency
  fsrs4anki_optimizer.ipynb
  package/Makefile
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/requirements.txt
  package/setup.py
Labels: invalid

#283 Fix/ensure w[5] >= 0.05 to alleviate ease hell
  fsrs4anki_optimizer.ipynb
  package/Makefile
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/setup.py
Labels: invalid

#285 Fix/Remove duplicated version number.
  package/Makefile
  package/setup.py
  package/version.txt
Labels: invalid

#286 Fix/select weights from best epoch
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/version.txt
Labels: invalid

#287 Feat/compare with sm-2
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/version.txt
Labels: enhancement

#288 Feat/speed up create time series
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/version.txt
Labels: enhancement

#289 Fix/python package publish
  .github/workflows/python-publish.yml
  package/Makefile
  package/pyproject.toml
  package/requirements.txt
  package/setup.py
Labels: bug

#292 Feat/return text & graph instead of print & show
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/__main__.py
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: enhancement

#296 Fix/replace print with return
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: invalid

#297 Doc/tutorial
  README.md
Labels: documentation

#302 Fix/remove unused code
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: invalid

#304 Fix/optional verbose outputs
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: invalid

#307 Feat/speed up find optimal retention
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: enhancement

#310 Fix/limit iterations
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: invalid

#311 Fix/empty batch when remainder == 0
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: bug

#312 Fix/not enough groups for pre-training
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: bug

#315 Fix/set terminal stability automatically
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: invalid

#319 Fix/only filter cram reviews
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: invalid

#324 Fix/filter out deleted cards' revlogs
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: invalid

#325 Fix/consider manual schedule revlog
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: invalid
