Repository open-spaced-repetition/fsrs4anki, pull requests merged in 2023-07, with the labels that each got.

#329 Doc/citation
  CITATION.cff
Labels: documentation

#330 Fix/warning if revlog_history.tsv is empty
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: bug

#334 Fix/strict revlog_start_date
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: invalid

#336 Feat/allow user to filter out suspended cards
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: enhancement

#340 Fix/add no_grad() for batch_predict()
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: invalid

#345 Fix/ensure post-lapse S lower than last S
  fsrs4anki_optimizer.ipynb
  fsrs4anki_scheduler.js
  fsrs4anki_scheduler_qt5.js
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: invalid

#349 Fix/remove unused filter & warning about inadequate data
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: invalid

#350 Fix/cosmetic-changes
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: invalid

#353 Fix/type & note & skip unused code
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: invalid

#357 Fix/too large initial stability for easy
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/__main__.py
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: invalid

#358 Feat/additive smoothing
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: enhancement

#360 Fix/sigam=1/count
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: invalid

#369 Fix/calibration skip empty ratings
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: bug

#371 Feat/outlier-detector
  archive/candidate/outlier_filter.ipynb
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: enhancement

#373 Fix/filter threshold
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: invalid

#368 Add optimizing options to readme
  README.md
Labels: documentation

#374 Feat/default parameters from collected data
  README.md
  fsrs4anki_optimizer.ipynb
  fsrs4anki_scheduler.js
  fsrs4anki_scheduler_qt5.js
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: enhancement

#376 Fix/loosen data limit in pretrain
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: invalid

#378 Fix/set init S to 30 for low reviews
  README.md
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
Labels: invalid

#381 Add wildcard support
  README.md
  package/fsrs4anki_optimizer/__main__.py
Labels: enhancement

#385 Feat/v4 simulator
  fsrs4anki_simulator.ipynb
Labels: enhancement

#388 Fix/skip files with inadequate reviews
  package/fsrs4anki_optimizer/__main__.py
  package/pyproject.toml
Labels: invalid

#392 Ecosystem/decouple-optimizer-package
  .github/workflows/python-publish.yml
  .gitmodules
  README.md
  fsrs4anki_optimizer.ipynb
  package/fsrs4anki_optimizer/__init__.py
  package/fsrs4anki_optimizer/__main__.py
  package/fsrs4anki_optimizer/fsrs4anki_optimizer.py
  package/pyproject.toml
  package/setup.py
Labels: ecosystem

#397 Fix/remove reviews with rating 0
  fsrs4anki_optimizer.ipynb
Labels: bug

#398 Fix/update to fsrs optimizer 4.5.0
  fsrs4anki_optimizer.ipynb
Labels: ecosystem

#400 Fix/update to FSRS Optimizer 4.5.5
  fsrs4anki_optimizer.ipynb
Labels: bug
