Repository open-spaced-repetition/fsrs4anki, pull requests merged in 2023-08, with the labels that each got.

#401 📃 Doc/(CLI optimizer): describe new arguments
  README.md
Labels: documentation

#403 Fix/update to fsrs optimizer 4.6.0
  fsrs4anki_optimizer.ipynb
Labels: ecosystem

#409 Doc/date format
  fsrs4anki_optimizer.ipynb
Labels: documentation

#410 Feat/filter out cards with specific flags
  fsrs4anki_optimizer.ipynb
Labels: enhancement

#413 Fix/init s out of order
  fsrs4anki_optimizer.ipynb
Labels: invalid

#418 Fix/conservative extrapolate value for S0
  fsrs4anki_optimizer.ipynb
Labels: invalid

#419 Fix/update to 4.9.0
  fsrs4anki_optimizer.ipynb
Labels: invalid

#427 Fix/remove outliers based on count
  README.md
  fsrs4anki_optimizer.ipynb
Labels: invalid

#433 Fix/loosen clamp for w[8] & w[10]
  fsrs4anki_optimizer.ipynb
Labels: invalid

#440 Doc/recommended retention range
  fsrs4anki_scheduler.js
  fsrs4anki_scheduler_qt5.js
Labels: documentation

#442 Doc/Update the compatibiltiy table.md
  README.md
Labels: documentation
